version: '3'

services:
  mongodb:
    image: mongo:4.4.23
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: LocalMongo
    volumes:
      - mongo-data:/data/db
      - ./backup:/backup

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    restart: always
    ports:
      - 1234:1234
    environment:
      HOST: 0.0.0.0
      PORT: 1234
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: LocalMongo
      CONN_NAME: LocalMongo
      ADMIN_MONGO_DEFAULT_CONNECTION: '{"connection_string": "mongodb://root:pass@mongodb:27017"}'
    depends_on:
      - mongodb

volumes:
  mongo-data:
  backup:
